### ISSUE TITLE
postcss-cssnext deprecated in favor of postcss-preset-env

### ISSUE THREAD

**Issue by pietermees** [timdp/rollup-plugin-cssnext#23]
I get the following warning:
```
rollup-plugin-cssnext > postcss-cssnext@2.11.0: 'postcss-cssnext' has been deprecated in favor of 'postcss-preset-env'. Read more at https://moox.io/blog/deprecating-cssnext/
```

**Comment by timdp** [comment]
Fixed in v0.1.0.

The package name doesn't make sense anymore but meh. Ultimately, I think it could be turned into something that only turns a CSS template into a render function, although I'm a bit on the fence about that use case as well.
